config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/bennyBlog', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "posts#index"
  resources :posts do
    member do
      post :like
    end
    collection do
      get :search
    end
    resources :comments,shallow: true,except:[:index,:new,:show]
  end

  get '/show_drafts', to: 'show_drafts#index'
  get '/show_publish', to: 'show_drafts#publish'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_post.rb
class FavoritePost < ApplicationRecord
      belongs_to :user
      belongs_to :post
    
end

app/models/post.rb
class Post < ApplicationRecord
      enum status: [ :publish,:draft ]
      validates :title, presence: true
      validates :content, presence: true
      has_rich_text :content
      belongs_to :user
      has_many :post_comments
      has_many :favorite_posts
      has_many :users,through: :favorite_posts
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
      belongs_to :user
      belongs_to :post
      has_rich_text :content
      validates :content, presence: true
      validates :post_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, length: {minimum: 3, maximum: 25} 
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :post_comments
  has_many :favorite_posts
  has_many :like_posts,through: :favorite_posts,source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post=Post.find(params[:post_id])
    @comment=@post.post_comments.new(comment_params)
    if current_user
    @comment.user_id=current_user.id
    else
    
    end

    if @comment.save
      flash[:notic]="留言成功"
      redirect_to @post
    else
      flash[:notic]="留言失敗"
      render 'posts/show'
    end

  end

  def destroy
    comment=PostComment.find(params[:id])
    comment.destroy
    redirect_to comment.post
  end
  
  private
  def comment_params
    params.require(:post_comment).permit(:content)
  end

  


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
      before_action :get_posts,only:[:show,:edit,:destroy,:update]
      before_action :clear_params,only:[:create,:update]
      before_action :authenticate_user!,except:[:index,:show,:search]
      def  index
        # @post=Post.order(id: :desc).where("!status")
        @post = Post.with_rich_text_content.order(id: :desc).page(params[:page]).per(5)
   
      end

      def new
        @post=Post.new
      end

      def like
        post=Post.find(params[:id])
        if current_user.like_posts.include?(post)
          current_user.like_posts.delete(post)
          post_count=post.favorite_posts.count
          render json: {status:0,amount:post_count}
        else
          current_user.like_posts << post
          post_count=post.favorite_posts.count
          render json: {status:1,amount:post_count}
        end
      end

      def  show
        require "image_processing/mini_magick"
        @comment=PostComment.new
        @comments=@post.post_comments.includes(:post).order(id: :desc)
        
      end

      def create
        @post=current_user.posts.new(@clear_params)
        if @post.save
         redirect_to root_path
        else
           render :new   
        end
      end

      def edit
      
      end

      def  update
     
       if @post.update(@clear_params)
            redirect_to root_path
       else
            render :edit  
       end
      end

      def destroy
          
            @post.destroy
            redirect_to root_path
      end

      def search
        keyword=params[:keyword]
        @post = Post.where("title like '%#{keyword}%' or content like '%#{keyword}%'").page(params[:page]).per(5) #.page(params[:page]).per(5)where()
      end


      private
      def clear_params
        @clear_params=params.require(:post).permit(:title,:content,:status)
      end
      def get_posts
            @post=Post.with_rich_text_content.find(params[:id])
      end
      def find_user
        @user=User.find(curret_user[:id])
      end
end  

app/controllers/show_drafts_controller.rb
class ShowDraftsController < ApplicationController
  
  def index
    @post=current_user.posts.where(status: :draft)
  end

  def publish
    @post=current_user.posts.where(status: :publish)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def slice_range str
    new_str=str.clone
    s_start=Regexp.new("<img src=")
    s_end=Regexp.new(">")
    if (str=~s_start)
      s_start= (str =~ s_start).to_i
      str=$'
      s_end=(str=~s_end).to_i
      str=new_str[(s_start+10)..(s_end+s_start+8)]
      return image_tag str,resize_to_limit:[100,100]
    end
    return
  end
end

app/helpers/show_drafts_helper.rb
module ShowDraftsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <!-- <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %> -->
  </figcaption>
</figure>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%=link_to "BLOG" , root_path,class:"navbar-brand"%>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <form action="/posts/search",method: get, class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search"  name="keyword" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>

      </ul>
      <ul class="navbar-nav mr-right">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle person-circle" id="navbarDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person"
              viewBox="0 0 16 16">
              <path fill-rule="evenodd"
                d="M10 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0zM8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm6 5c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
            </svg>User
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%if current_user %>
            <%=link_to "草稿" ,show_drafts_path,class:"dropdown-item"%>
            <%=link_to "發布文章" ,show_publish_path,class:"dropdown-item"%>
              <%=link_to "Log out" ,destroy_user_session_path,method: :delete,class:"dropdown-item"%>
                <%else%>
                  <%=link_to "Log in" ,new_user_session_path,class:"dropdown-item"%>
                  <%=link_to "sign in" ,new_user_registration_path,class:"dropdown-item"%>
                    <%end%>
          </div>
        </div>
      </ul>
    </div>
</nav>
<script>
  $('.dropdown-toggle').dropdown()
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>

  <%=render "./layouts/nav.html.erb"%>
  <%if flash[:notice]%>
  <div class="alert alert-success" role="alert" style="position:relative;z-index:1;"><%= flash[:notice]%>
    <button type=" button" class="close" data-dismiss="alert" aria-label="Close"><span
        aria-hidden="true">&times;</span></button></div>
  </div>
  <%end%>
 <div class="container"> <%= yield %></div>

</body>

</html>

app/views/posts/_form.html.erb
<%if post.errors.messages.any?%>
<ul>
      <%post.errors.full_messages.each do |msg|%>
      <li>
            <%=msg%>
      </li>
      <%end%>
</ul>
<%end%>
<div class="row row_box ">
      <div class="col-12"></div>
      <%= form_for post do |p| %>
     
      <div class="add_title col-12">
            <%=p.label :title%>
            <%=p.text_field :title%>
      </div>
      <div class="post_status col-12" style="left: 10%;">
          <%= p.radio_button(:status, :publish,:checked => true) %>
          <%= label_tag(:post_status, "發表") %>
          <%= p.radio_button(:status, :draft) %>
          <%= label_tag(:post_status, "草稿") %>
      </div>
      <div class="row col-12 row_content">
            <div class="col-1"></div>
            <div class="add_post col-9 ">
                  <%=p.rich_text_area :content,rows: 15%>
            </div>
            <div class="col-2"></div>
      </div>
      <div class="post_submit col-12">
            <%=p.submit%>
      </div>
      <%end%>
      <p><%=link_to "返  回",root_path,class:"show_back"%></p>
</div>

app/views/posts/edit.html.erb
<div class="container">
      <div class="add_b" style="position:relative;width:100vw;margin-bottom:50px">
            <h4 style=" left:20%; display:inline-block;position:absolute;">編輯文章</h4>
      </div>

      <%=render "form.html.erb",post:@post%>
</div>

app/views/posts/index.html.erb
<p>
      <%=link_to "<span>新增文章</span>" .html_safe,new_post_path,class:"add_bun ",style:" text-decoration: none;"%>
</p>
<%@post.each do |post|%>
      <div class="box row">
            <div class="post_title col-12">
                  <%=link_to post.title,post_path(post)%>
            </div>
            <div class="post_content row col-12 ">
                <div class="col-7 text"> <%=sanitize_action_text_content(post.content.body)%></div>
                <div class="col-4 text"> <%=slice_range post.content.body.to_s%></div>
               
            </div>
               <div class="row col-12 post_mos ">
                  <div class="post_birth col-6 offset-md-9 ">
                         <%=time_tag post.created_at%> 
                  </div>
                  <!-- <%if post.user==current_user && current_user%>
                        <div class=" row col-6 post_edit">
                              <p>
                                    <%=link_to "編輯" ,edit_post_path(post),class:"btn btn-warning col-12"%>
                              </p>
                              <p>
                                    <%=link_to "刪除" ,post_path(post),method: :delete,data:{confirm: "are you sure?"
                                          },class:"btn btn-danger col-12"%>
                              </p>
                        </div>
                  <%end%> -->
               </div>
      </div>
<%end%>

            <div class="row">
                  <div class="col-4"></div>
                  <div class="col-4">
                        <%= paginate @post%>
                  </div>
                  <div class="col-4"></div>
            </div>

app/views/posts/new.html.erb
<div class="container">

      <div class="add_b" style="position:relative;width:100vw;height:2%;margin-bottom:80px">
            <h4 style=" left:20%; display:inline-block;position:absolute;">新增文章</h4>
      </div>

      <%=render "form.html.erb",post:@post%>
</div>

app/views/posts/search.html.erb
<%@post.each do |post|%>
      <div class="box">
            <div class="post_title">
                  <%=link_to post.title,post_path(post)%>
            </div>
            <div class="post_content">
                  <%=post.content%>
            </div>
            <div class="post_birth">
                  <pre> <%=time_tag post.created_at%> </pre>
            </div>
            <%if post.user == current_user && current_user%>
              <div class="post_mos">
                 <p>
                   
                  <%=link_to "編輯" ,edit_post_path(post),class:"btn btn-warning"%>
                 </p>
                 <p>
                   <%=link_to "刪除" ,post_path(post),method: :delete,data:{confirm: "are you sure?" },class:"btn btn-danger"%>
                 </p>
              </div>
            <%end%>
      </div>
<%end%>
<div class="row">
      <div class="col-4"></div>
      <div class="col-4">
        <%= paginate @post%>
      </div>
      <div class="col-4"></div>
    </div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
  <div class="show_box">
    <div class="show_post_title col-12">
      <%=@post.title%> 
    </div>
    <div class="post_author col-12">
      <%=@post.user.try(:name) || 'unknow'%>
    </div>
    <div class="col-2"></div>
    <div class="show_post_content col-6">
      <pre> <%=@post.content%></pre>
    </div>
    <div class="col-2"></div>
  </div>
</div>



  <%= current_user.try(:name) || "訪客"%><br/>
  <a href="#" class="like_btn"  data-post-id="<%=@post.id%>">
    <%if current_user%>
      <%if current_user.like_posts.include?(@post)%>
        <i class="fas fa-thumbs-up"></i>
      <%else%>
        <i class="far fa-thumbs-up" ></i>
      <%end%>
    <%else%>
    <i class="far fa-thumbs-up" ></i>
    <%end%>
    </a> 
     
     <span class="like_amount"><%="#{@post.favorite_posts.count}"%></span> like this post
    <hr>
    <div class="post_comment">
      <div class="row">
        <div class="col-12 comment_user">
          <div class="row">
            <div class="col"></div>
              <button type="button" class="btn btn-info col" style="margin:5px;">facebook</button>
              <button type="button" class="btn btn-info col" style="margin:5px;">twitter</button>
              <div class="col-7" style="height:5px;"></div>
          </div>
        </div>
        <div class="col-12" style="height: 10px;"> </div>
        <div class="col-2 comment_user">
          <i class="fas fa-user"></i>
        </div>
        <div class="col-9">
          <%=form_for @comment ,url:post_comments_path(@post),class:"row" do |comment|%>
            <%=comment.rich_text_area :content,rows: 15%>
              <%=comment.submit "留言" ,class:"btn btn-outline-info col-2"%>
                <%end%>
        </div>
      </div>
    </div>
    <hr>

    <%@comments.each do |comment|%>
      <div class="card text-center">
        <div class="card-header">
          <%=comment.user.try(:email) || "guest" %> 留下足跡
        </div>
        <div class="card-body">
          <%=comment.content%>
        </div>
        <div class="card-footer text-muted">
          <%=time_ago_in_words comment.created_at%>
          <%if comment.user == current_user%>
          <%=link_to "刪除留言",comment_path(comment),method: :delete,data:{confirm:'sure?'} %>
          <%end%>
        </div>
      </div>
      <br />
      <%end%>

        <p>
          <%=link_to "返回" ,root_path,class:"show_back"%>
        </p>
</div>

app/views/show_drafts/_show.html.erb
<%posts.each do |post|%>
      <div class="box row">
            <div class="post_title col-12">
                  <%=link_to post.title,post_path(post)%>
            </div>
            <div class="post_content row col-12 ">
                <div class="col-7 text"> <%=sanitize_action_text_content(post.content.body)%></div>
                <div class="col-4 text"> <%=slice_range post.content.body.to_s%></div>
               
            </div>
               <div class="row col-12 post_mos ">
                  <div class="post_birth col-12 offset-md-8 ">
                         <%=time_tag post.created_at%> 
                  </div>
                  <div class="col-12 row">
                    <p class="col-2 offset-md-8"><%=link_to "編輯" ,edit_post_path(post),class:"btn btn-warning col-12"%></p>
                    <p class="col-2"><%=link_to "刪除" ,post_path(post),method: :delete,data:{confirm: "are you sure?" },class:"btn
                                btn-danger col-12"%></p>
                
              </div>
               </div>
      </div>
<%end%>

app/views/show_drafts/index.html.erb
<%=render "show" ,posts: @post%>

app/views/show_drafts/publish.html.erb
<%=render "show" ,posts: @post%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name),class:"badge badge-primary" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name),class:"badge badge-primary"%><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name),class:"badge badge-pill badge-warning" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>